### ISSUE TITLE
Caught By Teacher

### ISSUE THREAD

**Issue by ghost** [selfcommit/PassingNotes#2]
Hi there, first, thanks for this excellent app. It's nice knowing that the age-old art of passing notes in class is still alive and well. I feel like this is a good compromise between having to physically pass a note and doing the same action virtually.

However, my teacher caught me passing notes while my phone bumped up against my fellow classmate's. I was hoping you could add in the ability to pass notes by WiFi or maybe send them over text?

**Comment by PeterGrace** [comment]
+1 being able to text notes to peers would be great, can you add this?

**Comment by selfcommit** [comment]
@nextraztus 

We could encrypt the notes.  I suggest the following work around:
- Use a simple [Caesar cypher](http://en.wikipedia.org/wiki/Caesar_cipher) 
- After entering the 'encrypted' note into your phone, use the app to pass the encrypted note
- upon receiving the encrypted note, decrypt with pen and paper.

That should eliminate your teacher problem, be sure to dispose of any scrap paper after passing notes.
